### ISSUE TITLE
support scala-ide team re: type provider

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [scalamacros/paradise#61]
@xeno-by I think they are not capable of resolving these issues w/o your help
https://www.assembla.com/spaces/scala-ide/support/tickets/1002226#/activity/ticket:
https://www.assembla.com/spaces/scala-ide/support/tickets/1002372#/activity/ticket:

**Comment by xeno-by** [comment]
I think it's not the question of being capable, but rather the question of time and resources. Let me ask some questions on the scala-ide issue tracker, and maybe we'll figure something out. I have to admit that I know close to nothing about the presentation compiler, so that might be not as fast as we'd like.

**Comment by Andrei-Pozolotin** [comment]
great, thank you for looking into this.

**Comment by Andrei-Pozolotin** [comment]
re: https://github.com/scalamacros/paradise/commit/e07506d0fb05b8be3bfa4ed56fc4f5fc13dd8abf

`-Ymacro-expand` is not exposed in scala-ide preferences, should we ask them to make it user configurable?

![image](https://cloud.githubusercontent.com/assets/1622151/5789857/d8bea69c-9e41-11e4-91e7-889b005f7c6a.png)

**Comment by xeno-by** [comment]
`-Ymacro-expand:discard` is necessary to fix a presentation compiler issue. I don't think we can just disable it universally.

**Comment by SethTisue** [comment]
assuming obsolete, if that's wrong let's discuss
